--- 
apiVersion: v1
kind: Pod
metadata: 
  name: iottest
spec: 
  containers: 
    - 
      command: 
        - echo
        - SUCCESS
      image: sravangdocker/iottest:winserver
      imagePullPolicy: Always
      name: iottest
  imagePullSecrets:
    - name: myregistrykey
