--- 
apiVersion: v1
kind: Pod
metadata: 
  name: testhub
spec: 
  containers: 
    - 
      command: 
        - echo
        - SUCCESS
      image: sravangdocker/testhub:dev
      imagePullPolicy: Always
      name: testhub
  imagePullSecrets: 
    - 
      name: myregistrykey
